[pytest]
addopts =
    --reruns 1
    --screenshot=only-on-failure
    --video=retain-on-failure


markers =
    smoke: Critical path tests (Login, Checkout)
    regression: Full feature coverage
    cart: Shopping cart functionality
    login: Authentication tests
    ui: Visual and layout checks

testpaths = tests
